name: quatrex-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - black=24.8.0
  - blacken-docs=1.18.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cffi=1.17.1
  - cfgv=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - coverage=7.6.4
  - distlib=0.3.8
  - exceptiongroup=1.2.2
  - execnet=2.1.1
  - filelock=3.13.1
  - identify=2.5.5
  - iniconfig=2.0.0
  - isort=5.13.2
  - just=1.36.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - mpi=1.0.1
  - mpi4py=4.0.1
  - mpich=4.2.3
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nodeenv=1.7.0
  - numpy=2.1.3
  - openssl=3.4.0
  - packaging=24.1
  - pathspec=0.12.1
  - pip=24.2
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pre-commit=4.0.1
  - pre_commit=4.0.1
  - pycparser=2.21
  - pytest=8.3.3
  - pytest-cov=6.0.0
  - pytest-mpi=0.6
  - pytest-xdist=3.6.1
  - python=3.11.10
  - python_abi=3.11
  - pyyaml=6.0.2
  - readline=8.2
  - ruff=0.6.1
  - scipy=1.14.1
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.2
  - tzdata=2024b
  - ukkonen=1.0.1
  - virtualenv=20.26.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
